stages:
  - .pre
  - build
  - deploy

variables:
  CREATE_BRANCH: "false"
  USE_CASE_6: "false"

workflow:
  rules:
    - if: $USE_CASE_1 == "true"
      variables:
        UMBRELLA_GRADLE_COMMAND: "helmPackage -Pversion="
    - if: $USE_CASE_2 == "true"
      variables:
        UMBRELLA_GRADLE_COMMAND: "helmPackage -P$SOURCE_REPO-version=$SERVICE_CHART_VERSION -Pversion="
        BRANCH_NAME: $BRANCH_NAME
        GIT_BRANCH_NAME: $BRANCH_NAME-$SOURCE_REPO
        TAG: $SOURCE_REPO-$SERVICE_VERSION
    - if: $USE_CASE_4 == "true"
      variables:
        UMBRELLA_GRADLE_COMMAND: "helmPackage -P$SOURCE_REPO-version=$SERVICE_CHART_VERSION -Pversion="
        BRANCH_NAME: $BRANCH_NAME
        GIT_BRANCH_NAME: $BRANCH_NAME-$SOURCE_REPO
        TAG: $SOURCE_REPO-$SERVICE_VERSION
    - if: $CI_COMMIT_REF_NAME =~ /integration/
      when: always
      variables:
        USE_CASE_6: "true"
        BRANCH_NAME: $CI_COMMIT_REF_NAME
        GIT_BRANCH_NAME: $CI_COMMIT_REF_NAME
        UMBRELLA_GRADLE_COMMAND: "helmPackage -Pversion="
    - if: $CI_COMMIT_REF_NAME == master
      when: always
      variables:
        USE_CASE_8: "true"
    - if: $USE_CASE_3 == "true" || $USE_CASE_5 == "true"
      when: always

#workflow:
#  except:
#    changes:
#      - .gitlab-ci.yml

include:
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gitversion-ci-cd-plugin-extension.gitlab-ci.yml'
  - local: '/composite/prepare-environment-development.yml'
    rules:
      - if: $USE_CASE_1 == "true" && $USE_CASE_3 != "true" && $USE_CASE_5 != "true"
  - local: '/composite/prepare-service-for-environment.yml'
    rules:
      - if: ($USE_CASE_2 == "true" || $USE_CASE_4 == "true") && $CREATE_BRANCH != "true" && $USE_CASE_3 != "true" && $USE_CASE_5 != "true"
      - if: $USE_CASE_6 == "true" && $CREATE_BRANCH != "true"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

create-branch:
  stage: deploy
  script:
    - |
      export
      echo "create branch ${BRANCH_NAME}-${SOURCE_REPO}"
  rules:
    - if: ($USE_CASE_2 == "true" || $USE_CASE_4 == "true") && $CREATE_BRANCH == "true" && $USE_CASE_3 != "true" && $USE_CASE_5 != "true"
      when: always
    - when: never

delete_branch:
  stage: deploy
  script:
    - |
      export
      echo "Deleting Branch: $TARGET_BRANCH_NAME-$SOURCE_REPO"
  rules:
    - if: ($USE_CASE_3 == "true" || $USE_CASE_5 == "true")
      when: always
    - when: never

continuous-integration-prepare-environment:
  stage: deploy
  needs:
    - prepare-service-for-environment
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-4eyes-argocd'
    branch: 'master'
    strategy: depend
  rules:
    - if: $USE_CASE_6 == "true"
      when: always
    - when: never

cleanup-integration-environment:
  stage: deploy
  needs:
    - continuous-integration-prepare-environment
  variables:
    TARGET_BRANCH_NAME: $CI_COMMIT_REF_NAME
    BRANCH_NAME: $CI_COMMIT_REF_NAME
    USE_CASE_7: "true"
  trigger:
    include:
      - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
        ref: 'development'
        file: '/composite/cleanup-environment-integration.yml'
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true
  rules:
    - if: $USE_CASE_6 == "true"
      when: manual
    - when: never

release-ga:
  stage: deploy
  trigger:
    include:
      - local: '/composite/release-ga.yml'
    forward:
      pipeline_variables: true
      yaml_variables: true
    strategy: depend
  rules:
    - if: $USE_CASE_8 == "true"
      when: manual
    - when: never
