stages:
  - .pre
  - build
  - deploy

variables:
  UMBRELLA_CHART_NAME: "fsm-akka-helm-umbrella-chart-gitlab"

include:
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gitversion-ci-cd-plugin-extension.gitlab-ci.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gradle.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/helm-push-umbrella.yml'

determine-version:
  extends: .gitversion_function

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

prepare_environment:
  stage: deploy
  needs:
    - helm-push-umbrella
  trigger:
    project: org.salgar.fsm.akka/fsm-akka-dev-environment
    branch: 'development'
    strategy: depend