stages:
  - .pre
  - build
  - deploy

#workflow:
#  except:
#    changes:
#      - .gitlab-ci.yml

variables:
  BUILD_VERSION: $GitVersion_SemVer
include:
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gitversion-ci-cd-plugin-extension.gitlab-ci.yml'

determine-version:
  extends: .gitversion_function

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

package-helm-umbrella-chart:
  stage: deploy
  needs:
    - job: determine-version
      artifacts: true
  variables:
    BUILD_VERSION: $GitVersion_SemVer
    GRADLE_COMMAND: "helmPackage -Pversion="
  trigger:
    include:
      - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
        file: '/jobs/gradle.yml'
    strategy: depend

prepare-helm-umbrella-chart:
  stage: deploy
  needs:
    - job: determine-version
      artifacts: true
    - job: package-helm-umbrella-chart
      artifacts: true
  variables:
    CHART_NAME: "fsm-akka-helm-umbrella-chart-gitlab"
    CHART_VERSION: $GitVersion_SemVer
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
        file: '/jobs/helm-push.yml'
    strategy: depend

prepare_environment:
  stage: deploy
  needs:
    - prepare_helm_umbrella_chart
  trigger:
    project: org.salgar.fsm.akka/fsm-akka-dev-environment
    branch: 'development'
    strategy: depend