stages:
  - .pre
  - build
  - deploy

include:
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gitversion-ci-cd-plugin-extension.gitlab-ci.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gradle.yml'

determine-version:
  extends: .gitversion_function

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

prepare_helm_umbrella_chart:
  stage: deploy
  needs:
    - determine-version
    - build-gradle
  variables:
    UMBRELLA_CHART_NAME: "fsm-akka-helm-umbrella-chart-gitlab"
    CHART_VERSION: $GitVersion_SemVer
    GRADLE_COMMAND: "helmPackage -Pversion=$GitVersion_SemVer"
  trigger:
    include:
      - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
        file: '/jobs/helm-push-umbrella.yml'
    strategy: depend

prepare_environment:
  stage: deploy
  needs:
    - prepare_helm_umbrella_chart
  trigger:
    project: org.salgar.fsm.akka/fsm-akka-dev-environment
    branch: 'development'
    strategy: depend