include:
  - local: '/gitlab/composite/prepare-service-for-environment.yml'

continuous-epic-prepare-environment:
  stage: deploy
  needs:
    - prepare-service-for-environment
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-4eyes-argocd'
    branch: 'master'
    strategy: depend

cleanup-epic-environment:
  stage: deploy
  needs:
    - continuous-epic-prepare-environment
  variables:
    TARGET_BRANCH_NAME: $CI_COMMIT_REF_NAME
    BRANCH_NAME: $CI_COMMIT_REF_NAME
    USE_CASE_11: "true"
  trigger:
    include:
      - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
        ref: 'development'
        file: '/composite/cleanup-environment-integration.yml'
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true
  rules:
    - when: manual
